import js from "@eslint/js";
import prettierConfig from "eslint-config-prettier";

export default [
  js.configs.recommended,
  prettierConfig,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        // ── Browser / DOM globals ──
        window: "readonly",
        document: "readonly",
        console: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        sessionStorage: "readonly",
        localStorage: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        performance: "readonly",
        crypto: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Image: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        getComputedStyle: "readonly",
        // ── External libraries ──
        L: "readonly",
        maplibregl: "readonly",
        gsap: "readonly",
        ym: "readonly",
        dataLayer: "readonly",
        gtag: "readonly",
        // ── Vite / Node (config files) ──
        process: "readonly",
        __dirname: "readonly",
        import: "readonly",
        // ── Project globals (loaded via <script> tags) ──
        AppStorage: "readonly",
        AppDraw: "readonly",
        AppPoints: "readonly",
        AppWeapons: "readonly",
        AppShare: "readonly",
        AppAnalytics: "readonly",
        MapTiles: "readonly",
        MapRenderer: "readonly",
        MapViewport: "readonly",
        MapInteractions: "readonly",
        MapSpatial: "readonly",
        UIPanels: "readonly",
        UIInputs: "readonly",
        UIResults: "readonly",
        UIContextMenu: "readonly",
        LocaleManager: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      eqeqeq: "warn",
      "no-empty": ["error", { "allowEmptyCatch": true }],
      "no-var": "error",
      "prefer-const": "warn",
    },
  },
  {
    ignores: [
      "node_modules/**",
      "dist/**",
      "maps/**",
      "public/**",
      "assets/**",
      "vite.config.js",
    ],
  },
];
